server:
  port: 8080
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: appuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

  kafka:
    bootstrap-servers: my-cluster-kafka-bootstrap.kafka.svc:9092
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: appuser
    password: secret
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/appdb
    username: appuser
    password: secret
---
spring:
  config:
    activate:
      on-profile: k8s
  kafka:
    bootstrap-servers: my-cluster-kafka-bootstrap.kafka.svc:9092
  datasource:
    url: jdbc:postgresql://host.minikube.internal:5432/appdb
    username: appuser
    password: secret
